#!/bin/bash
usage()
{
    echo "Usage:"
    echo ""
    echo "   $0 FILE.root"
    echo ""
    echo ""
    exit
}
if [ -z $1 ]; then usage; fi
IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
echo "Your IP is set to:" $IP
/opt/X11/bin/xhost + $IP # For Mac OSX Catalina the XQuartz xhost is not in $PATH so full path is needed
INPUTROOTFILEPATH=$(realpath $1)
docker run \
    -it \
    --rm \
    --name fw9.4.1 \
    -e DISPLAY=$IP:0 \
    -e XAUTHORITY=/.Xauthority \
    --net host \
    -v ${HOME}/.Xauthority:/.Xauthority \
    -v ${INPUTROOTFILEPATH}:/cmsShow-9.4-1/file.root \
    sgnoohc/fireworks:9.4.1
